server:
  port: 8040
spring:
  application:
    name: miscroservice-gateway-zuul
eureka:
  client:
    service-url:
#      defaultZone: http://user:password123@peer1:8761/eureka/,http://user:password123@peer2:8762/eureka/
      defaultZone: http://user:password123@eureka_1:8761/eureka/,http://user:password123@eureka_2:8762/eureka/