server:
  port: 8000
spring:
  application:
    name: miscroservice-provider-user
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                      #指定数据源
    platform: h2                   #指定数据源类型
    schema: classpath:schema.sql   #指定h2数据库的建表脚本
    data: classpath:data.sql       #指定h2数据库的数据脚本
  logging:                         #配置日志级别，让hibernate打印执行sql
    level:
      root: INFO
      org.hibernate: INFO
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
#  zipkin:
#    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 0.2
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    healthcheck:
      enable: true
    serviceUrl:
#      defaultZone: http://user:password123@peer1:8761/eureka/,http://user:password123@peer2:8762/eureka/
      defaultZone: http://user:password123@eureka_1:8761/eureka/,http://user:password123@eureka_2:8762/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG