spring:
  application:
    name: miscroservice-discovery-eureka-ha
#  profiles: peer2
server:
  port: 8762
euraka:
  instance:
#    hostname: peer2
    hostname: eureka_2
  client:
    serviceUrl:
#      defaultZone: http://user:password123@peer1:8761/eureka/
      defaultZone: http://user:password123@eureka_1:8761/eureka/
security:
  basic:
    enabled: true            # 开启给予HTTP basic的认证
  user:
    name: user               # 配置登录的账户
    password: password123    # 配置登录的密码
